package com.studerb.store;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import org.joda.time.DateTime;

import com.studerb.model.BaseEntity;
import com.studerb.staff.Staff;

/**
 * Rental generated by hbm2java
 */
public class Rental extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private Integer rentalId;
	private Staff staff;
	private Customer customer;
	private Inventory inventory;
	private DateTime rentalDate;
	private DateTime returnDate;
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Rental() {}

	public Customer getCustomer() {
		return this.customer;
	}

	public Inventory getInventory() {
		return this.inventory;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public DateTime getRentalDate() {
		return this.rentalDate;
	}

	public Integer getRentalId() {
		return this.rentalId;
	}

	public DateTime getReturnDate() {
		return this.returnDate;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public void setInventory(Inventory inventory) {
		this.inventory = inventory;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public void setRentalDate(DateTime rentalDate) {
		this.rentalDate = rentalDate;
	}

	public void setRentalId(Integer rentalId) {
		this.rentalId = rentalId;
	}

	public void setReturnDate(DateTime returnDate) {
		this.returnDate = returnDate;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

}
