package com.studerb.store;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import com.studerb.geo.Address;
import com.studerb.model.BaseEntity;
import com.studerb.staff.Staff;

/**
 * Store generated by hbm2java
 */
public class Store extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private Staff manager;
	private Address address;
	private Set<Inventory> inventories = new HashSet<Inventory>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public Store() {}

	public Address getAddress() {
		return this.address;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public Staff getStaff() {
		return this.manager;
	}

	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	public void setStaff(Staff staff) {
		this.manager = staff;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

}
