//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.12.27 at 06:46:38 PM EST
//
@XmlJavaTypeAdapter(value = CalendarAdapter.class, type = Calendar.class)
@XmlAccessorType(XmlAccessType.NONE)
package com.studerb.hr.geo;

import java.util.Calendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.studerb.hr.employee.CalendarAdapter;

