package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA


/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	public final static int MAX_ADDRESS_1 = 50;
	public final static int MAX_ADDRESS_2 = 50;
	public final static int MAX_DISTRICT = 20;
	public final static int MAX_POSTAL_CODE = 10;
	public final static int MAX_PHONE = 20;

	private City city;
	private String address;
	private String address2;
	private String district;
	private String postalCode;
	private String phone;

	public Address() {}

	public Address(City city, String address, String district, String phone) {
		this.city = city;
		this.address = address;
		this.district = district;
		this.phone = phone;
	}

	public Address(City city, String address, String address2, String district, String postalCode, String phone) {
		this.city = city;
		this.address = address;
		this.address2 = address2;
		this.district = district;
		this.postalCode = postalCode;
		this.phone = phone;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
}
