package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City implements java.io.Serializable {
	private Country country;
	private String city;
	private Set<Address> addresses = new HashSet<Address>(0);

	public City() {}

	public City(Country country, String city) {
		this.country = country;
		this.city = city;
	}

	public City(Country country, String city, Date lastUpdate, Set<Address> addresses) {
		this.country = country;
		this.city = city;
		this.addresses = addresses;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
