package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Country generated by hbm2java
 */
public class Country implements java.io.Serializable {
	private String country;
	private Set<City> cities = new HashSet<City>();

	public Country() {}

	public Country(String country) {
		this.country = country;
	}

	public Country(String country, Date lastUpdate, Set<City> cities) {
		this.country = country;
		this.cities = cities;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
