package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import org.joda.time.DateTime;

/**
 * Customer generated by hbm2java
 */
public class Customer extends BaseEntity {
	public static final int MAX_FIRST_NAME = 45;
	public static final int MAX_LAST_NAME = 45;
	public static final int MAX_EMAIL = 50;

	private static final long serialVersionUID = 1L;
	private Address address;
	private Store store;
	private String firstName;
	private String lastName;
	private String email;
	private boolean active;
	private DateTime createDate = null;
	private Set<Rental> rentals = new HashSet<Rental>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public Customer() {}

	public Address getAddress() {
		return this.address;
	}

	public DateTime getCreateDate() {
		return this.createDate;
	}

	public String getEmail() {
		return this.email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public Set<Rental> getRentals() {
		return this.rentals;
	}

	public Store getStore() {
		return this.store;
	}

	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public void setCreateDate(DateTime createDate) {
		this.createDate = createDate;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public void setRentals(Set<Rental> rentals) {
		this.rentals = rentals;
	}

	public void setStore(Store store) {
		this.store = store;
	}

}
