package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

/**
 * FilmText generated by hbm2java
 */
public class FilmText extends BaseEntity {
	private String title;
	private String description;

	public FilmText() {}

	public FilmText(String title) {
		this.title = title;
	}

	public FilmText(String title, String description) {
		this.title = title;
		this.description = description;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
