package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.joda.time.DateTime;

/**
 * Film generated by hbm2java
 */
public class Film extends BaseEntity {

	private static final long serialVersionUID = 1L;
	public static final int MAX_TITLE = 255;
	public static final int MAX_DESCRIPTION = 65535;

	private Language languageByOriginalLanguageId;
	private Language languageByLanguageId;
	private String title;
	private String description;
	private DateTime releaseYear;
	private byte rentalDuration;
	private BigDecimal rentalRate;
	private Short length;
	private BigDecimal replacementCost;
	private String rating;
	private String specialFeatures;
	private Set<Actor> actors = new HashSet<Actor>();
	private Set<Category> categories = new HashSet<Category>();
	private Set<Inventory> inventories = new HashSet<Inventory>();

	public Film() {}

	public Set<Actor> getActors() {
		return actors;
	}

	public Set<Category> getCategories() {
		return categories;
	}

	public String getDescription() {
		return this.description;
	}

	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public Language getLanguageByLanguageId() {
		return this.languageByLanguageId;
	}

	public Language getLanguageByOriginalLanguageId() {
		return this.languageByOriginalLanguageId;
	}

	public Short getLength() {
		return this.length;
	}

	public String getRating() {
		return this.rating;
	}

	public DateTime getReleaseYear() {
		return this.releaseYear;
	}

	public byte getRentalDuration() {
		return this.rentalDuration;
	}

	public BigDecimal getRentalRate() {
		return this.rentalRate;
	}

	public BigDecimal getReplacementCost() {
		return this.replacementCost;
	}

	public String getSpecialFeatures() {
		return this.specialFeatures;
	}

	public String getTitle() {
		return this.title;
	}

	public void setActors(Set<Actor> actors) {
		this.actors = actors;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

	public void setLanguageByLanguageId(Language languageByLanguageId) {
		this.languageByLanguageId = languageByLanguageId;
	}

	public void setLanguageByOriginalLanguageId(Language languageByOriginalLanguageId) {
		this.languageByOriginalLanguageId = languageByOriginalLanguageId;
	}

	public void setLength(Short length) {
		this.length = length;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public void setReleaseYear(DateTime releaseYear) {
		this.releaseYear = releaseYear;
	}

	public void setRentalDuration(byte rentalDuration) {
		this.rentalDuration = rentalDuration;
	}

	public void setRentalRate(BigDecimal rentalRate) {
		this.rentalRate = rentalRate;
	}

	public void setReplacementCost(BigDecimal replacementCost) {
		this.replacementCost = replacementCost;
	}

	public void setSpecialFeatures(String specialFeatures) {
		this.specialFeatures = specialFeatures;
	}

	public void setTitle(String title) {
		this.title = title;
	}

}
