package com.studerb.model;

// Generated Nov 26, 2008 10:41:24 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.RandomStringUtils;
import org.apache.commons.lang.math.RandomUtils;

/**
 * Actor generated by hbm2java
 */
public class Actor extends BaseEntity {

	private static final long serialVersionUID = 1L;
	private static final int MAX_FIRST_NAME = 45;
	private static final int MAX_LAST_NAME = 45;

	private String firstName;
	private String lastName;
	private Set<Film> films = new HashSet<Film>();

	public Actor() {}

	public Actor(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public static Actor createRandom() {
		Actor actor = new Actor();
		actor.firstName = RandomStringUtils.randomAlphabetic(RandomUtils.nextInt(MAX_FIRST_NAME));
		actor.lastName = RandomStringUtils.randomAlphabetic(RandomUtils.nextInt(MAX_LAST_NAME));
		return actor;
	}

	public Set<Film> getFilms() {
		return films;
	}

	public String getFirstName() {
		return firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setFilms(Set<Film> films) {
		this.films = films;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
}
